name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 'true'

jobs:
  build:
    name: Build
    runs-on: macos-26
    strategy:
      matrix:
        number: [1, 2, 3, 4, 5]
      fail-fast: false
      max-parallel: 1
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v5.0.0
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Install Ccache
      run: brew install ccache
    - if: ${{ matrix.number == 1 }}
      name: Restore Ccache Directory
      uses: actions/cache/restore@v4.3.0
      with:
        key: ccache-iphonesimulator
        path: ccache
    - if: ${{ matrix.number != 1 }}
      name: Download Ccache Artifact
      uses: actions/download-artifact@v6.0.0
      with:
        name: ccache-iphonesimulator
        path: ccache
    - name: Install depot_tools
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
    - name: Fetch iOS code
      working-directory: chromium
      run: fetch --no-history ios
    - name: Copy .setup-gn
      run: cp -r ./src/.setup-gn ./chromium/
    - name: Set up the build
      working-directory: chromium/src
      run: python ios/build/tools/setup-gn.py
    - id: build
      name: Build Chromium
      working-directory: chromium/src
      run: autoninja -C out/Release-iphonesimulator web_view_signed_bundle
      env:
        CCACHE_BASEDIR: ${{ github.workspace }}/chromium
        CCACHE_DIR: ${{ github.workspace }}/ccache
        CCACHE_SLOPPINESS: time_macros
      continue-on-error: true
      timeout-minutes: 300
    - if: ${{ steps.build.outcome == 'success' }}
      name: Upload build artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: chromewebview-iphonesimulator
        path: chromium/src/out/Release-iphonesimulator/ChromeWebView.framework
        if-no-files-found: error
        retention-days: 1
        include-hidden-files: true
    - if: ${{ matrix.number == 5 || steps.build.outcome == 'success' }}
      name: Save Ccache directory
      uses: actions/cache/save@v4.3.0
      with:
        key: ccache-iphonesimulator
        path: |
          ccache
          !ccache/tmp
    - if: ${{ matrix.number != 5 && steps.build.outcome == 'success' }}
      name: Cancel Workflow
      uses: actions/github-script@v8.0.0
      with:
        script: |
          github.rest.actions.cancelWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          })
    - if: ${{ matrix.number != 5 && steps.build.outcome == 'success' }}
      name: Waiting for Cancel
      uses: actions/github-script@v8.0.0
      with:
        script: |
          const delay = ms => new Promise(res => setTimeout(res, ms));
  
          while (true) {
            core.info('Waiting for workflow to cancel ...');
            await delay(5000);
          }
    - if: ${{ matrix.number != 5 && steps.build.outcome == 'failure' }}
      name: Upload ccache artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: ccache-iphonesimulator
        path: |
          ccache
          !ccache/tmp
        if-no-files-found: error
        retention-days: 1
        overwrite: true
        include-hidden-files: true
