name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4.2.2
    - name: Install depot_tools
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
    - name: Fetch iOS code
      working-directory: ${{ github.workspace }}/chromium
      run: fetch ios
    - name: Build Chromium
      run: autoninja -C out/Debug-iphonesimulator gn_all
