name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 'true'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        target: [iphonesimulator]
      fail-fast: false
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4.2.2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_16.2.app/Contents/Developer'
    - name: Install iOS platforms
      run: xcodebuild -downloadPlatform iOS -buildVersion 18.2
    - name: Install ccache
      run: brew install ccache
    - name: Restore Ccache directory
      uses: actions/cache/save@v4.2.2
      with:
        key: ccache-${{ matrix.target }}
        path: ${{ github.workspace }}/.ccache
    - name: Install depot_tools
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
    - name: Fetch iOS code
      working-directory: ${{ github.workspace }}/chromium
      run: fetch --no-history ios
    - name: Copy .setup-gn
      run: cp -r ./src/.setup-gn ./chromium/
    - name: Set up the build
      working-directory: ${{ github.workspace }}/chromium/src
      run: python ios/build/tools/setup-gn.py
    - name: Build Chromium
      working-directory: ${{ github.workspace }}/chromium/src
      run: autoninja -C out/Release-${{ matrix.target }} web_view_signed_bundle
      env:
        CCACHE_BASEDIR: ${{ github.workspace }}/chromium
        CCACHE_DIR: ${{ github.workspace }}/.ccache
        CCACHE_SLOPPINESS: time_macros
      timeout-minutes: 30
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: ChromeWebView-${{ matrix.target }}
        path: ${{ github.workspace }}/chromium/src/out/Release-${{ matrix.target }}/ChromeWebView.framework
        if-no-files-found: error
        retention-days: 1
        compression-level: 0
    - if: always()
      name: Sleep
      run: sleep 600
    - if: always()
      name: Save Ccache directory
      uses: actions/cache/save@v4.2.2
      with:
        key: ccache-${{ matrix.target }}
        path: ${{ github.workspace }}/.ccache
