name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4.2.2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_16.2.app/Contents/Developer'
    - name: Install iOS platforms
      run: xcodebuild -downloadPlatform iOS -buildVersion 18.2
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.8
    - name: Install depot_tools
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
    - name: Fetch iOS code
      working-directory: ${{ github.workspace }}/chromium
      run: fetch --no-history ios
    - name: Set up the build
      working-directory: ${{ github.workspace }}/chromium/src
      run: python ios/build/tools/setup-gn.py
    - name: Copy .setup-gn
      run: cp -r ./src ./chromium/src
    - name: Show Targets
      run: ninja -t targets all
    - name: Build Chromium
      working-directory: ${{ github.workspace }}/chromium/src
      run: autoninja -C out/Release-iphoneos gn_all
      env:
        SCCACHE_GHA_ENABLED: "true"
        CCACHE_BASEDIR: ${{ github.workspace }}/chromium
        CCACHE_SLOPPINESS: time_macros
